=== marianagomes27/EPUB-projects/EPUB2019-Teste-A83222/regulamento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="trail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="longo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="infoespecifica" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="curto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="infoespecifica" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" name="caminhada">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="infoespecifica" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="regulamento">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="apresentacao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="designacao" type="xs:string"/>
                            <xs:element name="tipoprova" type="xs:string"/>
                            <xs:element name="distancia" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="organizacao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="pontosrelevantes"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="recomendacoes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="recomendacao" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="inscricoes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="info" type="xs:string"/>
                            <xs:element name="precos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="regulares"/>
                                        <xs:element name="especiais"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="periodo" type="xs:string"/>
                            <xs:element name="materialincluido">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="material"
                                            type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" ref="paragrafos"/>
                            <xs:element ref="trail"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dataehora">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="trail"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="percurso" type="xs:string"/>
                <xs:element name="materialobrigatorio">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="trail"/>
                            <xs:element name="infoadicional" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="marcacao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="pontosrelevantes"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tempolimite">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="trail"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abastecimentos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="trail"/>
                            <xs:element maxOccurs="unbounded" ref="paragrafos"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="premios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="localehoraent" type="xs:string"/>
                            <xs:element name="categorias">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="categoria">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="designacao" type="xs:string"/>
                                                  <xs:element name="descricao" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="classificacao" type="xs:string"/>
                            <xs:element name="premio" type="xs:string"/>
                            <xs:element name="periodocorrecao" type="xs:string"/>
                            <xs:element name="responsabilidade">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="pontosrelevantes"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="direitosimagem" type="xs:string"/>
                <xs:element name="cancelamento">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="paragrafos"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="responsabilidade">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="paragrafos"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="outros" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="paragrafos" type="xs:string"/>
    <xs:element name="pontosrelevantes" type="xs:string"/>
</xs:schema>

=== marianagomes27/EPUB-projects/EPUB2019-Teste-A83222/regulamento.xml
<?xml version="1.0" encoding="UTF-8"?>
<regulamento xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Mariana/Desktop/TESTE/Questao%202/regulamento.xsd">
    <apresentacao>
        <designacao> TRAIL DAS ANDORINHAS (4ª edição) – 15 de DEZEMBRO DE 2019 </designacao>
        <tipoprova>  Trail Running </tipoprova>
        <distancia> Trail Longo – 25Kms | Trail Curto 10kms – Caminhada – 8Kms </distancia>
    </apresentacao>
    <organizacao>
        <pontosrelevantes> Evento organizado pelo GRUPO DESPORTIVO DA GOMA, em parceria com a Câmara
            Municipal da Póvoa de Lanhoso. </pontosrelevantes>
        <pontosrelevantes> Gestão de inscrições da responsabilidade da PROZIS e cronometragem e classificações
            da CHRONO.  </pontosrelevantes>
    </organizacao>
    <recomendacoes>
        <recomendacao> É preciso ter a condição física adequada às características desta prova. </recomendacao>
        <recomendacao>É imprescindível beber em todos os abastecimentos e alimentar-se convenientemente. </recomendacao>
        <recomendacao>Devido às características tão especiais da prova, é recomendável a utilização de calçado
            e roupa adequada. 
        </recomendacao>
        <recomendacao> O participante deverá ter em conta a necessidade de levar abastecimento líquido e sólido
            adicional pessoalmente. 
        </recomendacao>
        <recomendacao> O dorsal do atleta é pessoal e intransmissível e deve ser usado á frente do atleta e de
            preferência a altura do peito, não é permitida qualquer alteração do dorsal sob pena de
            desclassificação. </recomendacao>
        
        
    </recomendacoes>
    <inscricoes>
        <info> A inscrição será feita através da página https://www.prozis.com/pt/pt/. No mesmo,
            consta toda a informação da prova. 
        </info>
        <precos>
            <regulares> TRAIL LONGO = 12,5€* , TRAIL CURTO = 10€* ,CAMINHADA = 5€*</regulares>
            <especiais> Grupos com 10 ou mais elementos * – Desconto de 10% sobre a opção seleccionada e
                referente à fase de inscrição. (devem solicitar ref. com desconto para
                geral.cronochip@gmail.com) </especiais>
        </precos>
        <periodo> A partir de 1 de Dezembroo de 2019 as inscrições sofrem um agravamento de 5€
            respectivamente. A partir desta mesma data, não serão aceites alterações/trocas de
            distâncias, atletas e/ou equipas, assim como alteração de nome de equipa.  </periodo>
        <materialincluido>
            <material> Dorsal 
            </material>
            <material>Oferta alusiva ao evento 
            </material>
            <material> Cronometragem/classificações (somente para as provas de Trail Longo e Trail Curto) </material>
            <material> Seguro de acidentes pessoal </material>
            <material> Abastecimentos (durante e no final da prova) </material>
            <material>Banhos/vestiários </material>
            <material> Massagem desportiva, no final da prova mediante disponibilidade dos
                massagistas presentes. 
            </material>
        </materialincluido>
        <paragrafos>Nota: Os menores deverão entregar o termo de responsabilidade, devidamente preenchido
            e assinado pelo tutor ou encarregado de educação, aquando do levantamento do dorsal;
            no acto do levantamento do dorsal só é necessário fazer-se acompanhar pelo documento
            de identificação. </paragrafos>
        <paragrafos> * Inclui 1 OFERTA (tshirt ou saco telemóvel impermeável, ou ainda outra oferta que a
            organização venha a conseguir) alusiva ao IV Trail das Andorinhas; Outra ofertas que a
            organização venha a conseguir junto dos patrocinadores. </paragrafos>
       
        <paragrafos> Não é possível ceder a participação a um terceiro em nenhuma das provas.  </paragrafos>
        
        <paragrafos> As inscrições não pagas após a fase de inscrição, serão anuladas e referência Multibanco
            bloqueadas, tendo o atleta de realizar uma nova inscrição sob nova fase inscrição! </paragrafos>
        
        <paragrafos> A organização assume a responsabilidade de entregar as ofertas do evento no
            secretariado nas inscrições efetuadas e pagas até 1 de Dezembro de 2019. A partir desta
            data, a organização aceita inscrições com agravamento do valor e sem garantias de
            conseguir entregar as ofertas. 
        </paragrafos>
        <paragrafos> A partir de 1 de Dezembro de 2019, não serão aceites alterações/trocas de distâncias,
            atletas e/ou equipas, assim como alteração de nome de equipa. 
        </paragrafos>
        
        <trail>
            <longo>
                <infoespecifica> participantes com idades iguais ou superiores a 16 anos, obtida a 31 de
                    Dezembro do presente ano. 
                </infoespecifica>
            </longo>
            <curto>
                <infoespecifica>participantes sem limitação de idade, desde que os menores se
                    façam acompanhar por um adulto. </infoespecifica>
            </curto>
            <caminhada>
                <infoespecifica> participantes sem limitação de idade, desde que os menores se
                    façam acompanhar por um adulto. </infoespecifica>
            </caminhada>
        </trail>
    </inscricoes>
    <dataehora>
        <trail>
            <longo>
                <infoespecifica>  8:30h </infoespecifica>
            </longo>
            <curto>
                <infoespecifica> 9:00h </infoespecifica>
            </curto>
            <caminhada>
                <infoespecifica> 9:00h </infoespecifica>
            </caminhada>
        </trail>
    </dataehora>
    <percurso> Trail ; Trail Curto ; Caminhada (serão disponibilizados na página do Facebook do evento). </percurso>
    <materialobrigatorio>
        <trail>
            <longo>
                <infoespecifica> Depósito de água ou equivalente com 1 litro de capacidade, no mínimo;
                    Telemóvel; Manta Térmica;</infoespecifica>
            </longo>
            <curto>
                <infoespecifica> Depósito de água ou equivalente com 0,5 litro de capacidade, no mínimo;
                    Telemóvel; Manta Térmica. 
                </infoespecifica>
            </curto>
            <caminhada>
                <infoespecifica> Telemóvel 
                </infoespecifica>
            </caminhada>
        </trail>
        <infoadicional> Penalização de 30 minutos pela falta de qualquer tipo material acima referido, no caso da
            vertente competitiva. A prova é realizada numa época em que as condições climatéricas
            podem ser de frio e chuva, pelo facto alertamos assim os participantes que cumpram este
            ponto para o seu próprio bem-estar e segurança. </infoadicional>
    </materialobrigatorio>
    <marcacao>
        <pontosrelevantes>  O percurso estará marcado com fitas de plástico de cor anunciada 15 minutos antes da
            partida pelo director da prova, assim como placas de sinalização, sendo obrigatória a
            passagem pelos controles estabelecidos</pontosrelevantes>
        <pontosrelevantes>  A cronometragem será efetuada de forma eletrónica. O chip estará no situado no dorsal. </pontosrelevantes>
    </marcacao>
    <tempolimite>
        <trail>
            <longo>
                <infoespecifica> O tempo máximo de conclusão do Trail Longo será de 4 horas. Na zona de separação de
                    percursos, os atletas do Trail que passarem após a hora estipulada antes da partida pelo
                    director de prova, serão encaminhados para o percurso do Trail Curto, cuja
                    classificação/cronometragem serão nesse caso contabilizadas como Trail Curto. 
                    Os participantes do Trail Longo que não passarem num determinado ponto do percurso
                    até determinada hora anunciada pela organização (após a conclusão de 2/3 do percurso)
                    serão aconselhados a abandonar a prova, pois nem a organização, nem os serviços de
                    assistência podem garantir a sua cobertura. Assim, os “Corredores Vassoura” ou o
                    responsável de cada controle terão poder para retirar da prova qualquer corredor se o seu
                    tempo na corrida ou se o seu estado de saúde assim aconselhar. </infoespecifica>
            </longo>
            <curto>
                <infoespecifica> No Trail Curto o tempo de conclusão será de 2,5 horas; 
                </infoespecifica>
            </curto>
            <caminhada>
                <infoespecifica> Não há informação especificada. </infoespecifica>
            </caminhada>
        </trail>
    </tempolimite>
    <abastecimentos>
        <trail>
            <longo>
                <infoespecifica> Abastecimento Líquido aos 5kms, Líquido e sólidos aos 15kms e 25kms;</infoespecifica>
            </longo>
            <curto>
                <infoespecifica>Abastecimento Líquido aos 5kms, Liquido e sólidos aos 10kms; 
                </infoespecifica>
            </curto>
            <caminhada>
                <infoespecifica> Não há informação.</infoespecifica>
            </caminhada>
        </trail>
        <paragrafos> (pontos que podem ser revistos, mas que estarão assinalados no dorsal no dia da prova) 
        </paragrafos>
    </abastecimentos>
    <premios>
        <localehoraent> A cerimónia de entrega de prémios será realizada junto à zona de meta, com previsão
            para as 13h30. A cerimónia protocolar será efetuada 15 minutos após o 3ª atleta referente
            a cada escalão terminar a prova, e quando as condições para tal estiverem reunidas. </localehoraent>
        <categorias>
            <categoria>
                <designacao> Masculinos: </designacao>
